/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Element-PTN/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePickerPanel: typeof import('element-plus/es')['ElDatePickerPanel']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    Message: typeof import('./src/components/Element-PTN/Dialog/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spacer: typeof import('./src/components/Element-PTN/Spacer.vue')['default']
    TitleCard: typeof import('./src/components/Style-FSC/TitleCard.vue')['default']
    TitleLineCard: typeof import('./src/components/Style-MFP/TitleLineCard.vue')['default']
    TitleLineWrapCard: typeof import('./src/components/Style-MFP/TitleLineWrapCard.vue')['default']
  }
}
